#!/usr/bin/env ruby

require 'mac-event-monitor'
require 'active_support/core_ext'

def main
  monitor = Mac::EventMonitor::Monitor.new
  monitor.add_listener(:key_down) do |event|
    if event.keycode == 36
      ainote
    end
  end

  monitor.run
end

def ainote
  system('afplay', Dir.glob('data/*').sample)
end

main
